version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  question-service:
    build: 
      context: ./backend/question-service
      target: dev
    ports:
      - 3001:3001
    volumes:
      - ./backend/question-service:/app
      - /app/node_modules
    environment:
      MONGODB_URL: mongodb://host.docker.internal:27017/peerprep
    
  peerprep-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    container_name: peerprep-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - peerprep-network

networks:
    peerprep-network:
