version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - question-service # To change to gateway-service

  question-service:
    build: 
      context: ./backend/question-service
      target: dev
    container_name: question-service
    ports:
      - 3002:3002
    volumes:
      - ./backend/question-service:/app
      - /app/node_modules
    env_file:
      - ./backend/question-service/.env
    environment:
      DB_HOST: peerprep-mongodb # Override localhost
    depends_on:
      - peerprep-mongodb
    networks:
      - peerprep-network

  peerprep-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    container_name: peerprep-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - peerprep-network

networks:
  peerprep-network:
