apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerprep-kafka
  template:
    metadata:
      labels:
        app: peerprep-kafka
    spec:
      containers:
      - name: peerprep-kafka-container
        image: confluentinc/cp-kafka:latest
        ports:
          - containerPort: 9092
          - containerPort: 29092
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: peerprep-zookeeper:2181
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://peerprep-kafka:9092,PLAINTEXT_HOST://localhost:29092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: peerprep-kafka
spec:
  selector:
    app: peerprep-kafka
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-host-port
      protocol: TCP
      port: 29092
      targetPort: 29092
  type: ClusterIP
