apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - name: collaboration-service-container
        image: rjkoh/cs3219-ay2425s1-project-g25-collaboration-service:latest
        ports:
          - containerPort: 3004
        env:
          - name: DB_HOST
            value: peerprep-mongodb.default.svc.cluster.local
          - name: KAFKA_HOST
            value: peerprep-kafka.default.svc.cluster.local
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
spec:
  selector:
    app: collaboration-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
