apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service-container
        image: rjkoh/cs3219-ay2425s1-project-g25-matching-service:latest
        ports:
          - containerPort: 3003
        env:
          - name: REDIS_HOST
            value: peerprep-redis.default.svc.cluster.local
          - name: DB_HOST
            value: peerprep-mongodb.default.svc.cluster.local
          - name: KAFKA_HOST
            value: peerprep-kafka.default.svc.cluster.local
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
