apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-container
        image: rjkoh/cs3219-ay2425s1-project-g25-user-service:latest
        ports:
          - containerPort: 3001
        env:
          - name: REDIS_HOST
            value: peerprep-redis.default.svc.cluster.local
          - name: DB_HOST
            value: peerprep-mongodb.default.svc.cluster.local
        resources:
          requests:
            cpu: "300m"
            memory: "768Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
