services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--bind", "0.0.0.0", "--requirepass", "yourpassword"]