version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - peerprep-network

networks:
  peerprep-network:
    driver: bridge
