apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: rjkoh/cs3219-ay2425s1-project-g25-frontend:latest
        ports:
          - containerPort: 3000
        env:
          - name: CHOKIDAR_USEPOLLING
            value: "true"
          - name: WATCHPACK_POLLING
            value: "true"
          - name: WDS_SOCKET_PORT
            value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
