apiVersion: apps/v1
kind: Deployment
metadata:
    name: peerprep-mongodb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: peerprep-mongodb
    template:
        metadata:
            labels:
                app: peerprep-mongodb
        spec:
            containers:
                - name: peerprep-mongodb
                  image: mongo:latest
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        value: "admin"
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        value: "password"
                  volumeMounts:
                      - name: init-script
                        mountPath: /docker-entrypoint-initdb.d/init-mongo.js
                        subPath: init-mongo.js
            volumes:
                - name: init-script
                  configMap:
                      name: init-mongo-script
---
apiVersion: v1
kind: Service
metadata:
    name: peerprep-mongodb
spec:
    ports:
        - port: 27017
          targetPort: 27017
    selector:
        app: peerprep-mongodb
    type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---

