apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerprep-redis
  template:
    metadata:
      labels:
        app: peerprep-redis
    spec:
      containers:
      - name: peerprep-redis-container
        image: redis:latest
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: peerprep-redis
spec:
  selector:
    app: peerprep-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
