version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_CLOUD_URI=mongodb+srv://whalejaywei:YXk4lSAsgu7FUhSI@cluster0.uqblys3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DB_LOCAL_URI=mongodb://mongo:27017/peerprepUserServiceDB
      - PORT=3001
      - POPULATE_DB=true
      - ENV=PROD
      - JWT_SECRET=you-can-replace-this-with-your-own-secret
    networks:
      - app_net
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mongo-data: