version: "3.9"

services:
  user-service:
    build: .
    container_name: user-service-container
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - peerprep-network

networks:
  peerprep-network:
    external: true
